export * from './Home';
export * from './Profile';
export * from './Shop';
export * from './Cart';
export * from './Login';
export * from './Register';
export * from './Landing';
export * from './About';
export * from './Contact';
export * from './ThankYou';
export * from './OrderHistory';
export * from './SingleProduct'